### ISSUE TITLE
Alire crate

### ISSUE THREAD

**Issue by yrashk** [AdaCore/ada-traits-containers#6]
I could not find this library on Alire. Is it abandoned/deprecated?

**Comment by briot** [comment]
(author of the library here, not an AdaCore employee anymore so not speaking for AdaCore): the library was never completed.  It was mostly an initial experiment to see how that we can get with Ada generics.  There are plenty of useful experiments here, most of them detailed in the doc/ directory, and that can be applied in other contexts.  It was also thought as the basis for SPARK-compatible containers.
I had nice hopes for the Graph part, which was always the part I preferred, but this wasn't completed (and then I left AdaCore).

The main drawback of the whole approach is on the user-friendliness side: using those containers require quite a lot of instantiation of generic packages, which is not that friendly.  I tried to get around that by providing high-level generic packages.  Likely this is the best approach for most users, and those who really want more control can do so by instantiating all the low-level packages.

If there is interest, and a community to improve, I still believe this whole traits-based approach has some potential.

**Comment by yrashk** [comment]
@briot Emmanuel, thank you so much for your feedback. Broadly speaking, what do you think is missing for this library to be revived/finalized and achieve its original intentions?

**Comment by briot** [comment]
If I remember well (though I haven't touched it in a few years), it doesn't have features parity with the standard Ada containers yet, though we are nearly there.   The graphs algorithms are pretty limited too.   My own fork of it has received more recent updates than the original AdaCore repository, so it is likely a better starting point.  I do not know whether AdaCore would wish to accept PR, but I think this project is irrelevant to them at this point.

**Comment by Fabien-Chouteau** [comment]
Hi @yrashk, as Emmanuel said this project is an experiment that was never completed. This is why we prefer not to publish it on Alire.

Best,
